
# Privatization {-}

Privatizing the Chemical Warfare Service (CWS) was a top priority of its chief officer Major General [Amos Fries](https://en.wikipedia.org/wiki/Amos_Fries) in the wake of WWI, as the longevity of the Service and its ability to pass weapons to law enforcement were not certain.

He was determined to prevent the CWS from being dissolved but saw a private industry marketed towards law enforcement and corrections as a parallel opportunity for the development and proliferation of chemical weapons [@Jones1978].
Similarly, he saw gas as a viable means of maintaining power for industrial bosses and colonizers seeking to crush labor and Indigenous uprisings [@Jones1978].

Fries authorized retired military officers retaining the patents for their inventions, establishing corporations, manufacturing propaganda to disseminate via the press, and creating an explicit commercial market [@Jones1978].


To facilitate the development of private companies, Fries provided free and heavily discounted chemical weapons and information to startups throughout his tenure [@Jones1978].
An early beneficiary was retired Major Stephen J. DeLanoy, who established his company Chemical Protection in New Jersey in the summer of 1921 [@Jones1978].
DeLanoy played a pivotal role in establishing early connections for sales and training with police departments and sought to cash in on the new market [@NYTimes1921_10_27]. 

Future industry leaders Federal Laboratories, Incorporated and Lake Erie Chemical Corporation benefited from continued support from the CWS, who provided field tests, technical assistance, referrals to suppliers that arm police departments throughout the '20s [@Jones1978].


## Federal Laboratories {-}

Retired Captain Ruben Lawrence of the Chemical Warfare Service (CWS) founded the Lawrence Company in Pittsburgh, PA, USA in 1922 with a gift from the CWS of a quart of [chloroacetophenone (CN)](https://en.wikipedia.org/wiki/Phenacyl_chloride), the only "tear gas" available at the time [@Jones1978].
Later that year, the CWS sold Lawrence 25 lbs of CN and twelve tear gas grenades, and provided him with a tour of the Edgewood Arsenal CN plant, technical specifications, and blueprints, defending the moves by stating

> "[Amos Fries], the Chief of the Chemical Warfare Service, desires to be of as great of assistance as possible to Mr. Lawrence in undertaking htis manufacturing venture."  [@Jones1978].

The following year, the Lawrence Company was rebranded as Federal Laboratories, Incorporated, and formally incorporated in Delaware on February 27th, although its principal office was still in Pittsburgh [@FLIvC; @FLIoc].
The company was led by John W. Young during the early years when they acquired the rights to patents from CWS researchers for a variety of weapons (for example, slow burning tear gas grenades), gaining a significant advantage in the burgeoning market [@Jones1978].



## Lake Erie {-}

The other prominent earlier supplier of chemical weapons in the US was Lake Erie Chemical Company of Cleveland, OH, USA [@Feigenbaum2018].
Lake Erie was also founded by a CWS veteran -- Chief Gas Officer Lt. Colonel Byron "Biff" Goss, a "respected chemist" and decorated soldier from the AEF [@Feigenbaum2018].
And similar to Federal Laboratories, Lake Erie was gifted CN from the CWS; they received 5 lbs of the chemical in 1926 [@Jones1978].
 
But where Federal Laboratories was focused on the domestic market, Goss leveraged his wartime connections in an effort to make Lake Erie the sole source of chemical weapons to the US military [@Feigenbaum2018].
Goss solicited help from his fellow CWS servicemembers in developing and testing a full line of tear gas grenades that used a bursting charge to vaporize a solution of CN [@Jones1978].
The Service conducted a series of tests of Lake Erie’s commercial line at Edgewood Arsenal in 1927, providing critical user feedback and facilitating development on items like the "Blind-X-Shell" (designed to be shot at point-blank range into someone's face) [@Feigenbaum2018].
Early on, Goss also developed a propaganda arm of Lake Erie based on twisted scientific research  [@Feigenbaum2018].

Goss remained chairman of the board until he passed in 1964 [@FindAGrave].


## The Results {-}

The campaign to establish a private chemical weapons industry was extremely successful.

By the close of Fries' command of the CWS in 1929, police departments in major USA cities like Chicago, New York, San Francisco, Philadelphia, and Cleveland had purchased chemical weapons [@Feigenbaum2014].
Sales abroad were burgeoning as well, in particular in British and American colonial territories in India, Panama, and Hawaii [@Feigenbaum2014].

The 1930s would see multiple public domestic uses of tear gas, in particular to break up labor movements, that garnered public attention and some scrutiny, but actually acted as advertising for their chemical weapons [@Steuben1950].
And in the decades to come both Federal Laboratories and Lake Erie would see considerable growth and development [@Jones1978].

### Hands-On Domestic Deployments {-}

The development of the industrial complex continued well beyond Fries' tenure, aided by horrific domestic "field tests" of tear gas in which protesters and bystanders were murdered by officers _**and salesmen**_ who used the incidents to sell their state-of-the-art chemical weapons.

The "[Bonus Army](https://en.wikipedia.org/wiki/Bonus_Army)" camps made of veterans lobbying in Washington, D.C. for overdue wartime payments were swept by the National Guard on July 29th, 1932, using tear gas weapons that filled the camp with fire, smoke, and gas [@Feigenbaum2014].
Two men were killed during the forcible eviction as was an infant child who reportedly died of asphyxiation from the gas [@Feigenbaum2014].

Federal Laboratories and Lake Erie both had sales representatives embedded with police during the "[Big Strike](https://en.wikipedia.org/wiki/1934_West_Coast_waterfront_strike)" of 1934 in San Francisco to demonstrate the "effectiveness" of their weapons in actual riot situations and to drum up interest in purchasing their wares [@Steuben1950].
Reports indicate they brought $20,000 -- $25,000 worth of chemical weapons to the Strike and instructed officers in how to use them.
On the "[Bloody Thursday](https://en.wikipedia.org/wiki/1934_West_Coast_waterfront_strike#%22Bloody_Thursday%22)" of July 5th, one striking worker was killed by a Federal Laboratories rep who shot him in the head with a gas projectile [@Steuben1950].

The event is eerily reminiscent of the US Marshals agent shooting protester Donavan LaBella in the head with a gas projectile nearly a century later during the uprising in Portland of 2020 [@Levinson2020].

Thanks to quick-acting field medics, Donavan survived the frontal lobe skull fracture, although not without lasting physical, congitive, and behavioral impacts [@Levinson2020].
The Federal Laboratories representative that killed the protester in 1934 was not shy about it, gloating in a letter back to his boss (John W. Young), who praised him during US Senate testimony [Steuben1950].
