
# Federal Laboratories {-}

## Federal Labs {-}

In the inter-war era, under the direction of John W. Young, Federal Laboratories found a large market for chemical weapons in private industry strike breaking and welcomed yet-to-become-notorious individuals to invest in and help lead the company [@Senate1939_6_3].
For example, W. W. Groves, the president of the Railway Audit & Inspection Company, Incorporated. (a Pinkerton-style detective agency known for labor espionage and strikebreaking [@Senate1937_46_3]), was on the board of directors from 1930 to 1935 and held stock in the company after his departure [@Senate1939_6_3].

United States Senate inquiries were launched into labor practices, including the use of chemical munitions, and Young was called to testify [@Youngphoto; @Senate1939_6_3].
Despite repeated testimony from medical authorities on the significant harmful effects of tear gas, Young kept a straight face while making statements like "tear gas can't injure" [@Senate1939_6_3].


## Breeze Corporations {-}

In 1937, Breeze Corporations, Incorporated purchased the vast majority of stock in Federal Laboratories, Incorporated, effectively making it a subsidiary [@FLIvC; @Time1939].
Thus far, it appears to me that Federal Laboratories kept its operations as they were prior to the purchase, but Breeze Corps. was a tumultuous parent.

[Breeze Corporations, Inc.](https://en.wikipedia.org/wiki/Breeze-Eastern) (publicly traded as BZC on the New York Stock Exchange) was created from "obscure origins" by inventor Joseph J. Mascuch, a former bumper salesman [@NJHoF; @Time1939].
Mascuch created Breeze in 1926  by consolodating multiple manufacturing companies [@NJHoF; @BCIoc].  

Mascuch elected two "representatives of a Wall Street group headed by Securities Salesman John J. Bergen [that] sold Breeze common stock" as directors of Breeze in 1938 [@Time1939].
Although the Securities and Exchage Commision (SEC) placed a stop order on Breeze selling stock in August 1938, asserting an overstatement of value potential, the company made amenments as the order was removed [@Time1939].

While the company survived the SEC, Mascuch did not -- US Attorney John T. Chaill arrested him on perjury charges in May 1939 [@Time1939].
Mascuch was found guilty on two counts of perjury and sentenced to two years in prison and charged a $4,000 fine [@NYTimes1939; @Time1939]

The company was left to contend with suits brought by 79 shareholders [@Time1939], but survived and was turning a solid profit with Federal Laboratories in the early 1940s [@TheMorningNews]


## TransTechnology Corporation {-}

In 1982, aerospace-defense manufacturer TransTechnology Corporation (1981 net income $3.7 million) bought Breeze Corporations (1981 net icome $2.5 million) in a "friendly" purchase [@Ross1982].  
  
TransTech was incorporated in 1962 in California and was traded publicly prior to the purchase, as well [@TToc].

Chairman of TransTechnology Arch C. Scurlock remained in his position and Mascuch, somehow still president of Breeze, became vice chairman [@Ross1982].



## Mace Securities Incorporated {-}

