
# Lake Erie Chemical {-}




Lake Erie sold in 1962 https://www.leagle.com/decision/1965768181so2d5871622

a new Lake Erie is created in 1962 by J Jacques Stone, Anita Derby, and Doris Hammes
https://businesssearch.ohiosos.gov/?=businessDetails/312898

The "Bangor Punta Conglomerate" bought Smith & Wesson in 1964
merges it with Lake Eerie Chemical, rebrands the chem weapons line Smith & Wesson Chemical Company 
https://www.youtube.com/watch?v=zXwFIbAF5C0
https://i1.wp.com/www.forgottenweapons.com/wp-content/uploads/2020/06/20070067-593-2560x1997-1.jpeg?ssl=1
Rock Creek Ohio
https://en.wikipedia.org/wiki/Bangor_Punta


Bangor Punta  1968
https://www.gjenvick.com/BangorPunta/Corporate/AnnualReports/1968/index.html

8a~9QY Purta Alegre Sugar
COMpany 'ost treir Cuban sugar
to t~eCutan5" it may have been
a blessin~ to tnem in disguise.
But the ·si 'ver I ining of the·
~x~ropr'ation cloud was that it
opened the eyes of the men behind
Bangor Punta to new investment
opportunities. with a little
help from their friends in the
U.S. government, -who gave them
generous tax advantages, Bangor
Punta Alegre Sugar Company became
Bangor Punta Alegre Holding
Company; it dabbled in lots of ,
things, as holding companies are
supposed ·o--~ewelry manUfacturing
in Puerto Rico, rai I roads in
fv\a i ne •••
But the boys at Bangor Punta
realized from their experience
;n Cuba t~at the trend is toward
global revolutipn. And when
there's a trend toward revolution,
there's a trend for imperial
powers to bUy 1015 of guns and
assorted instruments of oppression
to use against the revolutionaries.

So the Bangor Punta Alegre
Holding Compenv bought a gun
company--Smitr and Wesson. And
after they bought the gun company,
the' formed a Law Enforce_
mert Group of companies Cail of
which Bangor Punta had bought)
to put out a new line of products
wi th high demand: IMCE marufactured
by General Ordinance Equipment
Corporation, CN tear cas madE
by Lake Erie Chemical comp~ny,
and the gadgets of the cop business,
sirens and such, produced
by Dominator Company, whose name
tells just where they'd like to
be at.
And YO ~a~~et their st If,
Bangor p.nta arlyertises in the
Police C~ief ~ournal of the
Internat onal Association of
Chieis of Polke), that they
have "agents i pri. cipal cities
of the USA arJ in every country
of th~ free world." Because
that's where t~e revolution's
coming, and the men b~hind
Bangor Punta want to be there
to make money ti IJ the revolution
https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwjb9rjdzPzwAhXLpJ4KHQonAoY4ChAWMA56BAgSEAM&url=http%3A%2F%2Fubu-mirror.ch%2Fmedia%2Ftext%2Fvp%2Fbuddhist_third_class_junkmail_oracle_nov_1968.pdf&usg=AOvVaw1RiNo77G2V9LPxXKeR6pSH



### 1984

Bangor Punta was bought out
Smith & Wesson was sold off
